# Generated by Django 3.2 on 2022-02-12 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_banner_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
    ]
