# Generated by Django 3.2 on 2022-02-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('A', 'Created'), ('B', 'Payed For'), ('C', 'In Transit'), ('D', 'Complete')], default='A', max_length=1),
        ),
    ]
