# Generated by Django 3.2 on 2022-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('A', 'Created'), ('B', 'Payment Recieved'), ('C', 'In Transit'), ('D', 'Complete')], default='A', max_length=1),
        ),
    ]
